import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { Public_Sans } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
const publicSans = Public_Sans({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} `}>
        {/* <body className={`${geistSans.variable} ${geistMono.variable} ${inter.className} `}> */}
        {children}
      </body>
    </html >
  );
}
