// 'use client'
import { Inter, Protest_Guerrilla } from "next/font/google";
import { Public_Sans } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

const publicSans = Public_Sans({
  subsets: ['latin'],
  display: 'swap',
});

const protestGuerrilla = Protest_Guerrilla({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});


export const metadata = {
  title: "MidvertHub",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${publicSans.className} `}>
        {/* <body className={`${geistSans.variable} ${geistMono.variable} ${inter.className} `}> */}
        {children}
      </body>
    </html >
  );
}
